config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  resources :thoughts, except: :index do
    collection do
      scope module: 'thoughts' do
        resources :unresolved, only: [:index], as: 'unresolved_thoughts'
        resources :resolved, only: [:index], as: 'resolved_thoughts'
      end
    end
    resource :resolution, only: [:new, :create]
  end
  resources :tags, only: :index do
    scope module: 'tags' do
      resources :unresolved_thoughts, only: :index
      resources :resolved_thoughts, only: :index
    end
  end

  namespace :api do
    resources :thoughts, only: %i[index create update destroy]
  end

  authenticated do
    root to: 'thoughts#show'
  end
  root to: redirect('/users/sign_in')
end

app/models/resolution.rb
# frozen_string_literal: true

class Resolution
  include ActiveModel::Model

  attr_accessor :thought, :text

  validates :thought, :text, presence: true

  def initialize(thought, params = nil)
    self.thought = thought
    self.text = params[:text] if params.present?
  end

  def save
    thought.update(resolution: text) if valid?
  end
end

app/controllers/resolutions_controller.rb
# frozen_string_literal: true

class ResolutionsController < ApplicationController
  def new
    @thought = current_user.thoughts.find(params[:thought_id])
    @resolution = Resolution.new(@thought)
  end

  def create
    @thought = current_user.thoughts.find(params[:thought_id])
    @resolution = Resolution.new(@thought, resolution_params)
    if @resolution.save
      redirect_to root_path, notice: 'Thought resolution recorded.'
    else
      render :new
    end
  end

  private

  def resolution_params
    params.require(:resolution).permit(:text)
  end
end

app/views/resolutions/new.html.erb
<% if @resolution.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @resolution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'thoughts/detail' %>

<%= form_for @resolution, url: thought_resolution_path do |f| %>
  <div class="form-group">
    <%= f.text_area :text, placeholder: 'Resolution', rows: 3, class: 'form-control input-lg' %>
  </div>
  <div class="row">
    <div class="hidden-xs hidden-sm col-md-4"></div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="form-group">
        <%= f.submit 'Mark Resolved', class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="form-group">
        <%= link_to 'Cancel', @thought, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  </div>
<% end %>