config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  resources :thoughts, except: :index do
    collection do
      scope module: 'thoughts' do
        resources :unresolved, only: [:index], as: 'unresolved_thoughts'
        resources :resolved, only: [:index], as: 'resolved_thoughts'
      end
    end
    resource :resolution, only: [:new, :create]
  end
  resources :tags, only: :index do
    scope module: 'tags' do
      resources :unresolved_thoughts, only: :index
      resources :resolved_thoughts, only: :index
    end
  end

  namespace :api do
    resources :thoughts, only: %i[index create update destroy]
  end

  authenticated do
    root to: 'thoughts#show'
  end
  root to: redirect('/users/sign_in')
end

app/models/thought.rb
# frozen_string_literal: true

class Thought < ApplicationRecord
  belongs_to :user
  acts_as_taggable

  validates :text, presence: true

  scope :resolved, -> { where.not(resolution: nil) }
  scope :unresolved, -> { where(resolution: nil) }

  def unresolved?
    !resolved?
  end

  def resolved?
    resolution.present?
  end
end

app/controllers/api/thoughts_controller.rb
# frozen_string_literal: true

module Api
  class ThoughtsController < ApiController
    def index
      render json: current_user.thoughts
    end

    def create
      thought = current_user.thoughts.build(thought_params)
      if thought.save
        render json: thought, status: :created
      else
        render json: thought.errors, status: :unprocessable_entity
      end
    end

    def update
      thought = current_user.thoughts.find(params[:id])
      if thought.update(thought_params)
        render json: thought, status: :ok
      else
        render json: thought.errors, status: :unprocessable_entity
      end
    end

    def destroy
      thought = current_user.thoughts.find(params[:id])
      thought.destroy!
      head :ok
    end

    private

    def new_thought_params
      {}.tap do |new_thought_params|
        if params[:tag].present?
          name = ActsAsTaggableOn::Tag.find(params[:tag]).name
          new_thought_params[:tag_list] = name
        end
      end
    end

    def thought_params
      thought_params = params.require(:thought).permit(:text, :resolution)
      if (tags = params[:thought][:tags])
        thought_params = thought_params.merge(tag_list: tags)
      end
      thought_params
    end
  end
end

app/controllers/thoughts/resolved_controller.rb
# frozen_string_literal: true

module Thoughts
  class ResolvedController < ApplicationController
    def index
      @thoughts = current_user.resolved_thoughts.order(:text)
    end
  end
end

app/controllers/thoughts/unresolved_controller.rb
# frozen_string_literal: true

module Thoughts
  class UnresolvedController < ApplicationController
    def index
      @thoughts = current_user.unresolved_thoughts.order(:text)
    end
  end
end

app/controllers/thoughts_controller.rb
# frozen_string_literal: true

class ThoughtsController < ApplicationController
  def show
    if (thought_id = params[:id])
      @thought = current_user.thoughts.find(thought_id)
    else
      if current_user.unresolved_thoughts.empty?
        redirect_to new_thought_path
        return
      end
      @thought = random_thought
    end
    flash[:last_thought_id] = @thought.id
  end

  def new
    @thought = current_user.thoughts.build(new_thought_params)
  end

  def create
    @thought = current_user.thoughts.build(thought_params)
    if @thought.save
      redirect_to @thought, notice: 'Thought created.'
    else
      render :new
    end
  end

  def edit
    thought_id = params[:id]
    @thought = current_user.thoughts.find(thought_id)
  end

  def update
    @thought = current_user.thoughts.find(params[:id])
    if @thought.update(thought_params)
      redirect_to @thought, notice: 'Thought updated.'
    else
      render :edit
    end
  end

  def destroy
    @thought = current_user.thoughts.find(params[:id])
    @thought.destroy!
    redirect_to root_path, notice: 'Thought deleted.'
  end

  private

  def random_thought
    if other_thoughts.any?
      other_thoughts.sample
    else
      current_user.unresolved_thoughts.sample
    end
  end

  def other_thoughts
    last_id = flash[:last_thought_id]
    @other_thoughts ||=
      current_user.unresolved_thoughts.where('id <> ?', last_id)
  end

  def new_thought_params
    {}.tap do |new_thought_params|
      if params[:tag].present?
        name = ActsAsTaggableOn::Tag.find(params[:tag]).name
        new_thought_params[:tag_list] = name
      end
    end
  end

  def thought_params
    params.require(:thought).permit(:text, :tag_list)
  end
end

app/helpers/thought_helper.rb
# frozen_string_literal: true

module ThoughtHelper
  def thought_html(thought)
    thought.text.gsub("\n", '<br />')
  end
end

app/views/thoughts/_detail.html.erb
<div class="panel panel-default thought-panel">
  <div class="panel-body">
    <p class="lead"><%= thought_html(@thought).html_safe %></p>
    <% @thought.tags.each do |tag| %>
      <%= link_to tag, tag_unresolved_thoughts_path(tag.id), class: 'btn btn-primary btn-sm' %>
    <% end %>
    <% if @thought.resolved? %>
      <p class="lead"><%= @thought.resolution %></p>
    <% end %>
    <%= yield %>
  </div>
</div>

app/views/thoughts/_form.html.erb
<% if @thought.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @thought.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @thought do |f| %>
  <div class="form-group">
    <%= f.text_area :text, placeholder: 'Thought', rows: 3, class: 'form-control input-lg' %>
  </div>
  <div class="form-group">
    <%= f.text_field :tag_list, placeholder: 'Tags (separated by spaces)', class: 'form-control input-lg', autocapitalize: :off %>
  </div>
  <div class="row">
    <div class="hidden-xs hidden-sm col-md-6"></div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="form-group">
        <%= f.submit 'Save Thought', class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="form-group">
        <%= link_to 'Cancel', @thought.new_record? ? root_path : @thought, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/thoughts/_list.html.erb
<ul class="list-group">
  <% @thoughts.each do |thought| %>
    <li class="list-group-item"><%= link_to thought.text, thought_path(thought) %></li>
  <% end %>
</ul>

app/views/thoughts/edit.html.erb
<h2>Edit Thought</h2>

<%= render 'form' %>

app/views/thoughts/new.html.erb
<h2>Add Thought</h2>

<%= render 'form' %>

app/views/thoughts/show.html.erb
<%= render 'detail' do %>
  <div class="pull-right">
    <div class="dropdown visible-xs-block visible-sm-block">
      <button class="btn btn-default" type="button" id="thoughtActionMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="thoughtActionMenu">
        <% if @thought.unresolved? %>
          <li><%= link_to 'Resolve', new_thought_resolution_path(@thought) %></li>
        <% end %>
        <li><%= link_to 'Edit', edit_thought_path(@thought) %></li>
        <li><%= link_to 'Delete', @thought, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
    <div class="hidden-xs hidden-sm">
      <% if @thought.unresolved? %>
        <%= link_to 'Resolve', new_thought_resolution_path(@thought), class: 'btn btn-default btn-sm' %>
      <% end %>
      <%= link_to 'Edit', edit_thought_path(@thought), class: 'btn btn-default btn-sm' %>
      <%= link_to 'Delete', @thought, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="hidden-xs hidden-sm col-md-6"></div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="form-group">
      <%= link_to 'Next', root_path, class: 'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-3">
    <div class="form-group">
      <%= link_to 'Add Thought', new_thought_path, class: 'btn btn-default btn-lg btn-block' %>
    </div>
  </div>
</div>