config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  resources :thoughts, except: :index do
    collection do
      scope module: 'thoughts' do
        resources :unresolved, only: [:index], as: 'unresolved_thoughts'
        resources :resolved, only: [:index], as: 'resolved_thoughts'
      end
    end
    resource :resolution, only: [:new, :create]
  end
  resources :tags, only: :index do
    scope module: 'tags' do
      resources :unresolved_thoughts, only: :index
      resources :resolved_thoughts, only: :index
    end
  end

  namespace :api do
    resources :thoughts, only: %i[index create update destroy]
  end

  authenticated do
    root to: 'thoughts#show'
  end
  root to: redirect('/users/sign_in')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mindset</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mindset-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Mindset', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="mindset-navbar">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to 'Thoughts', unresolved_thoughts_path %></li>
              <li><%= link_to 'Tags', tags_path %></li>
              <li><%= link_to 'Add Thought', new_thought_path(tag: @tag) %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Register', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>

      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
          <% if notice %>
            <div class="alert alert-success"><%= notice %></div>
          <% end %>
          <% if alert %>
            <div class="alert alert-danger"><%= alert %></div>
          <% end %>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>